---
- name: Install GPU drivers for ubuntu
  hosts: all
  become: yes
  tasks:

  - name: Update apt-get repo and cache
    apt:
      update_cache: yes
      cache_valid_time: 600

  - name: Install ubuntu drivers package
    apt:
      pkg:
        - ubuntu-drivers-common
      state: present

  - name: Install nvidia drivers using ubuntu drivers
    ansible.builtin.shell:
      cmd: ubuntu-drivers --gpgpu install