---
- name: Download CUDA installation file on all servers
  hosts: all
  tasks:
    - name: Ensure the destination directory exists
      ansible.builtin.file:
        path: "/home/administrator/temp"
        state: directory
        mode: '0755'

    - name: Download the CUDA installation file
      ansible.builtin.get_url:
        url: http://172.17.16.11/cuda_12.6.3_560.35.05_linux.run
        dest: "/home/administrator/temp/cuda_12.6.3_560.35.05_linux.run"
        mode: '0777'