- name: Install Prometheus and Node Exporter on all nodes
  hosts: all
  become: true
  vars:
    prometheus_version: "3.2.1"
    node_exporter_version: "1.9.1"
    prometheus_user: prometheus
    node_exporter_user: node_exporter
    prometheus_install_dir: /opt/prometheus
    prometheus_config_dir: /etc/prometheus
    prometheus_data_dir: /opt/prometheus/data
    prometheus_binary_dir: /usr/local/bin
    node_exporter_binary_path: /usr/local/bin/node_exporter
  tasks:
    - name: Ensure prometheus and node_exporter users exist
      ansible.builtin.user:
        name: "{{ item }}"
        shell: /sbin/nologin
        system: true
        create_home: false
      loop:
        - "{{ prometheus_user }}"
        - "{{ node_exporter_user }}"
    - name: Create Prometheus directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_user }}"
        mode: '0755'
      loop:
        - "{{ prometheus_install_dir }}"
        - "{{ prometheus_config_dir }}"
        - "{{ prometheus_data_dir }}"

    - name: Download Prometheus
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: /tmp/prometheus.tar.gz
        mode: '0644'

    - name: Extract Prometheus
      ansible.builtin.unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp/
        remote_src: true
    - name: Install Prometheus binaries
      ansible.builtin.copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "{{ prometheus_binary_dir }}/{{ item }}"
        mode: '0755'
        remote_src: true
      loop:
        - prometheus
        - promtool
    - name: Write Prometheus config
      ansible.builtin.copy:
        dest: "{{ prometheus_config_dir }}/prometheus.yml"
        mode: '0644'
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

            - job_name: 'node_exporter'
              static_configs:
                - targets: ['localhost:9100']
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_user }}"
    - name: Create Prometheus systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus Monitoring
          Wants=network-online.target
          After=network-online.target

          [Service]
          User={{ prometheus_user }}
          Group={{ prometheus_user }}
          Type=simple
          ExecStart={{ prometheus_binary_dir }}/prometheus \
            --config.file={{ prometheus_config_dir }}/prometheus.yml \
            --storage.tsdb.path={{ prometheus_data_dir }}


          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Download Node Exporter
      ansible.builtin.get_url:
        url: >
          https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/
          node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
        dest: /tmp/node_exporter.tar.gz
        mode: '0644'

    - name: Extract Node Exporter
      ansible.builtin.unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp/
        remote_src: true
    - name: Install Node Exporter binary
      ansible.builtin.copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "{{ node_exporter_binary_path }}"
        mode: '0755'
        owner: root
        group: root
        remote_src: true
    - name: Create Node Exporter systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User={{ node_exporter_user }}
          Group={{ node_exporter_user }}
          Type=simple
          ExecStart={{ node_exporter_binary_path }}

          [Install]
          WantedBy=multi-user.target
        mode: '0644'
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
    - name: Enable and start Prometheus
      ansible.builtin.systemd:
        name: prometheus
        enabled: true
        state: started
    - name: Enable and start Node Exporter
      ansible.builtin.systemd:
        name: node_exporter
        enabled: true
        state: started
